security:
  enable_authenticator_manager: true

  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  encoders:
    App\Infrastructure\Security\User:
      algorithm: auto

  providers:
    users:
      id: App\Infrastructure\Security\UserProvider

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      custom_authenticator: App\Infrastructure\Security\LoginFormUserAuthenticator
      logout: ~

  access_control:
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/profile, roles: ROLE_USER }
    - { path: ^/, roles: PUBLIC_ACCESS }
