version: '3.8'

services:
  adminer:
    image: adminer:4.7
    links:
      - "postgres:db"
    ports:
      - "8080:8080"
    environment:
      ADMINER_DESIGN: haeckel

  postgres:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_PASSWORD: dpac
      POSTGRES_USER: dpac
      POSTGRES_DB: dpac

  yarn:
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    build:
      context: ./docker/yarn
    volumes:
      - .:/app

  php:
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    build:
      context: ./docker/php
    links:
      - "postgres:db"
    volumes:
      - .:/app
    environment:
      COMPOSER_HOME: /tmp/composer
    depends_on:
      - postgres
      - yarn

  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "8000:80"
    volumes:
      - .:/app
    depends_on:
      - php
